name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Run Lint
      uses: ./gradlew lintDebug

    - name: upload html test report
      uses: actions/upload-artifact@v3

      with:
         name: index.html
         path: app/build/reports/lint-results-debug.html

