name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build



  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
=======
    - uses: actions/checkout@v3
      name: Checkout the code
>>>>>>> 59d86bef8d94a486485778139f9fdb219d0d5891


<<<<<<< HEAD
    - name: upload html test report
      uses: actions/upload-artifact@v3
=======
    - uses: ./gradlew lintDebug
      name: Run Lint


    - uses: actions/upload-artifact@v3
      name: upload html test report

>>>>>>> 59d86bef8d94a486485778139f9fdb219d0d5891

      with:
         name: index.html
         path: app/build/reports/lint-results-debug.html

  unit-test:
     needs: [lint]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the code
         uses: actions/checkout@v3

       - name: Run tests
         uses: ./gradlew test

       - name: upload test report
         uses: actions/upload-artifact@v3

         with:
           name: unit_test_report
           path: app/build/reports/tests/testDebugUnitTest/
           

